import React, { useState } from "react";

import {
  Container,
  Select,
  Heading,
  SimpleGrid,
  FormLabel,
  Stack,
  Button,
} from "@chakra-ui/react";

const StateCityData = () => {
  const statescities = [
    {
      AndhraPradesh: [
        "Adoni",
        "Amalapuram",
        "Anakapalle",
        "Anantapur",
        "Bapatla",
        "Bheemunipatnam",
        "Bhimavaram",
        "Bobbili",
        "Chilakaluripet",
        "Chirala",
        "Chittoor",
        "Dharmavaram",
        "Eluru",
        "Gooty",
        "Gudivada",
        "Gudur",
        "Guntakal",
        "Guntur",
        "Hindupur",
        "Jaggaiahpet",
        "Jammalamadugu",
        "Kadapa",
        "Kadiri",
        "Kakinada",
        "Kandukur",
        "Kavali",
        "Kovvur",
        "Kurnool",
        "Macherla",
        "Machilipatnam",
        "Madanapalle",
        "Mandapeta",
        "Markapur",
        "Nagari",
        "Naidupet",
        "Nandyal",
        "Narasapuram",
        "Narasaraopet",
        "Narsipatnam",
        "Nellore",
        "Nidadavole",
        "Nuzvid",
        "Ongole",
        "Palacole",
        "Palasa Kasibugga",
        "Parvathipuram",
        "Pedana",
        "Peddapuram",
        "Pithapuram",
        "Ponnur",
        "Proddatur",
        "Punganur",
        "Puttur",
        "Rajahmundry",
        "Rajam",
        "Rajampet",
        "Ramachandrapuram",
        "Rayachoti",
        "Rayadurg",
        "Renigunta",
        "Repalle",
        "Salur",
        "Samalkot",
        "Sattenapalle",
        "Srikakulam",
        "Srikalahasti",
        "Srisailam Project (Right Flank Colony) Township",
        "Sullurpeta",
        "Tadepalligudem",
        "Tadpatri",
        "Tanuku",
        "Tenali",
        "Tirupati",
        "Tiruvuru",
        "Tuni",
        "Uravakonda",
        "Venkatagiri",
        "Vijayawada",
        "Vinukonda",
        "Visakhapatnam",
        "Vizianagaram",
        "Yemmiganur",
        "Yerraguntla",
      ],
      Assam: [
        "Barpeta",
        "Bongaigaon City",
        "Dhubri",
        "Dibrugarh",
        "Diphu",
        "Goalpara",
        "Guwahati",
        "Jorhat",
        "Karimganj",
        "Lanka",
        "Lumding",
        "Mangaldoi",
        "Mankachar",
        "Margherita",
        "Mariani",
        "Marigaon",
        "Nagaon",
        "Nalbari",
        "North Lakhimpur",
        "Rangia",
        "Sibsagar",
        "Silapathar",
        "Silchar",
        "Tezpur",
        "Tinsukia",
      ],
      Bihar: [
        "Araria",
        "Arrah",
        "Arwal",
        "Asarganj",
        "Aurangabad",
        "Bagaha",
        "Barh",
        "Begusarai",
        "Bettiah",
        "Bhabua",
        "Bhagalpur",
        "Buxar",
        "Chhapra",
        "Darbhanga",
        "Dehri-on-Sone",
        "Dumraon",
        "Forbesganj",
        "Gaya",
        "Gopalganj",
        "Hajipur",
        "Jamalpur",
        "Jamui",
        "Jehanabad",
        "Katihar",
        "Kishanganj",
        "Lakhisarai",
        "Lalganj",
        "Madhepura",
        "Madhubani",
        "Maharajganj",
        "Mahnar Bazar",
        "Makhdumpur",
        "Maner",
        "Manihari",
        "Marhaura",
        "Masaurhi",
        "Mirganj",
        "Mokameh",
        "Motihari",
        "Motipur",
        "Munger",
        "Murliganj",
        "Muzaffarpur",
        "Narkatiaganj",
        "Naugachhia",
        "Nawada",
        "Nokha",
        "Patna*",
        "Piro",
        "Purnia",
        "Rafiganj",
        "Rajgir",
        "Ramnagar",
        "Raxaul Bazar",
        "Revelganj",
        "Rosera",
        "Saharsa",
        "Samastipur",
        "Sasaram",
        "Sheikhpura",
        "Sheohar",
        "Sherghati",
        "Silao",
        "Sitamarhi",
        "Siwan",
        "Sonepur",
        "Sugauli",
        "Sultanganj",
        "Supaul",
        "Warisaliganj",
      ],
      Chandigarh: ["Chandigarh*"],
      Chhattisgarh: [
        "Ambikapur",
        "Bhatapara",
        "Bhilai Nagar",
        "Bilaspur",
        "Chirmiri",
        "Dalli-Rajhara",
        "Dhamtari",
        "Durg",
        "Jagdalpur",
        "Korba",
        "Mahasamund",
        "Manendragarh",
        "Mungeli",
        "Naila Janjgir",
        "Raigarh",
        "Raipur*",
        "Rajnandgaon",
        "Sakti",
        "Tilda Newra",
      ],
      Delhi: ["Delhi", "New Delhi*"],
      Goa: ["Mapusa", "Margao", "Marmagao", "Panaji*"],
      Gujarat: [
        "Adalaj",
        "Ahmedabad",
        "Amreli",
        "Anand",
        "Anjar",
        "Ankleshwar",
        "Bharuch",
        "Bhavnagar",
        "Bhuj",
        "Chhapra",
        "Deesa",
        "Dhoraji",
        "Godhra",
        "Jamnagar",
        "Kadi",
        "Kapadvanj",
        "Keshod",
        "Khambhat",
        "Lathi",
        "Limbdi",
        "Lunawada",
        "Mahesana",
        "Mahuva",
        "Manavadar",
        "Mandvi",
        "Mangrol",
        "Mansa",
        "Mahemdabad",
        "Modasa",
        "Morvi",
        "Nadiad",
        "Navsari",
        "Padra",
        "Palanpur",
        "Palitana",
        "Pardi",
        "Patan",
        "Petlad",
        "Porbandar",
        "Radhanpur",
        "Rajkot",
        "Rajpipla",
        "Rajula",
        "Ranavav",
        "Rapar",
        "Salaya",
        "Sanand",
        "Savarkundla",
        "Sidhpur",
        "Sihor",
        "Songadh",
        "Surat",
        "Talaja",
        "Thangadh",
        "Tharad",
        "Umbergaon",
        "Umreth",
        "Una",
        "Unjha",
        "Upleta",
        "Vadnagar",
        "Vadodara",
        "Valsad",
        "Vapi",
        "Vapi",
        "Veraval",
        "Vijapur",
        "Viramgam",
        "Visnagar",
        "Vyara",
        "Wadhwan",
        "Wankaner",
      ],
      Haryana: [
        "Bahadurgarh",
        "Bhiwani",
        "Charkhi Dadri",
        "Faridabad",
        "Fatehabad",
        "Gohana",
        "Gurgaon",
        "Hansi",
        "Hisar",
        "Jind",
        "Kaithal",
        "Karnal",
        "Ladwa",
        "Mahendragarh",
        "Mandi Dabwali",
        "Narnaul",
        "Narwana",
        "Palwal",
        "Panchkula",
        "Panipat",
        "Pehowa",
        "Pinjore",
        "Rania",
        "Ratia",
        "Rewari",
        "Rohtak",
        "Safidon",
        "Samalkha",
        "Sarsod",
        "Shahbad",
        "Sirsa",
        "Sohna",
        "Sonipat",
        "Taraori",
        "Thanesar",
        "Tohana",
        "Yamunanagar",
      ],
      Jharkhand: [
        "Adityapur",
        "Bokaro Steel City",
        "Chaibasa",
        "Chatra",
        "Chirkunda",
        "Medininagar (Daltonganj)",
        "Deoghar",
        "Dhanbad",
        "Dumka",
        "Giridih",
        "Gumia",
        "Hazaribag",
        "Jamshedpur",
        "Jhumri Tilaiya",
        "Lohardaga",
        "Madhupur",
        "Mihijam",
        "Musabani",
        "Pakaur",
        "Patratu",
        "Phusro",
        "Ramgarh",
        "Ranchi*",
        "Sahibganj",
        "Saunda",
        "Simdega",
        "Tenu dam-cum-Kathhara",
      ],
      Karnataka: [
        "Adyar",
        "Afzalpur",
        "Arsikere",
        "Athni",
        "Bengaluru",
        "Belagavi",
        "Ballari",
        "Chikkamagaluru",
        "Davanagere",
        "Gokak",
        "Hubli-Dharwad",
        "Karwar",
        "Kolar",
        "Lakshmeshwar",
        "Lingsugur",
        "Maddur",
        "Madhugiri",
        "Madikeri",
        "Magadi",
        "Mahalingapura",
        "Malavalli",
        "Malur",
        "Mandya",
        "Mangaluru",
        "Manvi",
        "Mudalagi",
        "Mudabidri",
        "Muddebihal",
        "Mudhol",
        "Mulbagal",
        "Mundargi",
        "Nanjangud",
        "Nargund",
        "Navalgund",
        "Nelamangala",
        "Pavagada",
        "Piriyapatna",
        "Puttur",
        "Rabkavi Banhatti",
        "Raayachuru",
        "Ranebennuru",
        "Ramanagaram",
        "Ramdurg",
        "Ranibennur",
        "Robertson Pet",
        "Ron",
        "Sadalagi",
        "Sagara",
        "Sakaleshapura",
        "Sindagi",
        "Sanduru",
        "Sankeshwara",
        "Saundatti-Yellamma",
        "Savanur",
        "Sedam",
        "Shahabad",
        "Shahpur",
        "Shiggaon",
        "Shikaripur",
        "Shivamogga",
        "Surapura",
        "Shrirangapattana",
        "Sidlaghatta",
        "Sindhagi",
        "Sindhnur",
        "Sira",
        "Sirsi",
        "Siruguppa",
        "Srinivaspur",
        "Tarikere",
        "Tekkalakote",
        "Terdal",
        "Talikota",
        "Tiptur",
        "Tumkur",
        "Udupi",
        "Vijayapura",
        "Wadi",
        "Yadgir",
      ],
      Karnatka: ["Mysore"],
      Kerala: [
        "Adoor",
        "Alappuzha",
        "Attingal",
        "Chalakudy",
        "Changanassery",
        "Cherthala",
        "Chittur-Thathamangalam",
        "Guruvayoor",
        "Kanhangad",
        "Kannur",
        "Kasaragod",
        "Kayamkulam",
        "Kochi",
        "Kodungallur",
        "Kollam",
        "Kottayam",
        "Kozhikode",
        "Kunnamkulam",
        "Malappuram",
        "Mattannur",
        "Mavelikkara",
        "Mavoor",
        "Muvattupuzha",
        "Nedumangad",
        "Neyyattinkara",
        "Nilambur",
        "Ottappalam",
        "Palai",
        "Palakkad",
        "Panamattom",
        "Panniyannur",
        "Pappinisseri",
        "Paravoor",
        "Pathanamthitta",
        "Peringathur",
        "Perinthalmanna",
        "Perumbavoor",
        "Ponnani",
        "Punalur",
        "Puthuppally",
        "Koyilandy",
        "Shoranur",
        "Taliparamba",
        "Thiruvalla",
        "Thiruvananthapuram",
        "Thodupuzha",
        "Thrissur",
        "Tirur",
        "Vaikom",
        "Varkala",
        "Vatakara",
      ],
      MadhyaPradesh: [
        "Alirajpur",
        "Ashok Nagar",
        "Balaghat",
        "Bhopal",
        "Ganjbasoda",
        "Gwalior",
        "Indore",
        "Itarsi",
        "Jabalpur",
        "Lahar",
        "Maharajpur",
        "Mahidpur",
        "Maihar",
        "Malaj Khand",
        "Manasa",
        "Manawar",
        "Mandideep",
        "Mandla",
        "Mandsaur",
        "Mauganj",
        "Mhow Cantonment",
        "Mhowgaon",
        "Morena",
        "Multai",
        "Mundi",
        "Murwara (Katni)",
        "Nagda",
        "Nainpur",
        "Narsinghgarh",
        "Narsinghgarh",
        "Neemuch",
        "Nepanagar",
        "Niwari",
        "Nowgong",
        "Nowrozabad (Khodargama)",
        "Pachore",
        "Pali",
        "Panagar",
        "Pandhurna",
        "Panna",
        "Pasan",
        "Pipariya",
        "Pithampur",
        "Porsa",
        "Prithvipur",
        "Raghogarh-Vijaypur",
        "Rahatgarh",
        "Raisen",
        "Rajgarh",
        "Ratlam",
        "Rau",
        "Rehli",
        "Rewa",
        "Sabalgarh",
        "Sagar",
        "Sanawad",
        "Sarangpur",
        "Sarni",
        "Satna",
        "Sausar",
        "Sehore",
        "Sendhwa",
        "Seoni",
        "Seoni-Malwa",
        "Shahdol",
        "Shajapur",
        "Shamgarh",
        "Sheopur",
        "Shivpuri",
        "Shujalpur",
        "Sidhi",
        "Sihora",
        "Singrauli",
        "Sironj",
        "Sohagpur",
        "Tarana",
        "Tikamgarh",
        "Ujjain",
        "Umaria",
        "Vidisha",
        "Vijaypur",
        "Wara Seoni",
      ],
      Maharashtra: [
        "Ahmednagar",
        "Akola",
        "Akot",
        "Amalner",
        "Ambejogai",
        "Amravati",
        "Anjangaon",
        "Arvi",
        "Aurangabad",
        "Bhiwandi",
        "Dhule",
        "Kalyan-Dombivali",
        "Ichalkaranji",
        "Kalyan-Dombivali",
        "Karjat",
        "Latur",
        "Loha",
        "Lonar",
        "Lonavla",
        "Mahad",
        "Malegaon",
        "Malkapur",
        "Mangalvedhe",
        "Mangrulpir",
        "Manjlegaon",
        "Manmad",
        "Manwath",
        "Mehkar",
        "Mhaswad",
        "Mira-Bhayandar",
        "Morshi",
        "Mukhed",
        "Mul",
        "Greater Mumbai*",
        "Murtijapur",
        "Nagpur",
        "Nanded-Waghala",
        "Nandgaon",
        "Nandura",
        "Nandurbar",
        "Narkhed",
        "Nashik",
        "Navi Mumbai",
        "Nawapur",
        "Nilanga",
        "Osmanabad",
        "Ozar",
        "Pachora",
        "Paithan",
        "Palghar",
        "Pandharkaoda",
        "Pandharpur",
        "Panvel",
        "Parbhani",
        "Parli",
        "Partur",
        "Pathardi",
        "Pathri",
        "Patur",
        "Pauni",
        "Pen",
        "Phaltan",
        "Pulgaon",
        "Pune",
        "Purna",
        "Pusad",
        "Rahuri",
        "Rajura",
        "Ramtek",
        "Ratnagiri",
        "Raver",
        "Risod",
        "Sailu",
        "Sangamner",
        "Sangli",
        "Sangole",
        "Sasvad",
        "Satana",
        "Satara",
        "Savner",
        "Sawantwadi",
        "Shahade",
        "Shegaon",
        "Shendurjana",
        "Shirdi",
        "Shirpur-Warwade",
        "Shirur",
        "Shrigonda",
        "Shrirampur",
        "Sillod",
        "Sinnar",
        "Solapur",
        "Soyagaon",
        "Talegaon Dabhade",
        "Talode",
        "Tasgaon",
        "Thane",
        "Tirora",
        "Tuljapur",
        "Tumsar",
        "Uchgaon",
        "Udgir",
        "Umarga",
        "Umarkhed",
        "Umred",
        "Uran",
        "Uran Islampur",
        "Vadgaon Kasba",
        "Vaijapur",
        "Vasai-Virar",
        "Vita",
        "Wadgaon Road",
        "Wai",
        "Wani",
        "Wardha",
        "Warora",
        "Warud",
        "Washim",
        "Yavatmal",
        "Yawal",
        "Yevla",
      ],
      Manipur: ["Imphal*", "Lilong", "Mayang Imphal", "Thoubal"],
      Meghalaya: ["Nongstoin", "Shillong*", "Tura"],
      Mizoram: ["Aizawl", "Lunglei", "Saiha"],
      Nagaland: [
        "Dimapur",
        "Kohima*",
        "Mokokchung",
        "Tuensang",
        "Wokha",
        "Zunheboto",
      ],
      Odisha: [
        "Balangir",
        "Baleshwar Town",
        "Barbil",
        "Bargarh",
        "Baripada Town",
        "Bhadrak",
        "Bhawanipatna",
        "Bhubaneswar*",
        "Brahmapur",
        "Byasanagar",
        "Cuttack",
        "Dhenkanal",
        "Jatani",
        "Jharsuguda",
        "Kendrapara",
        "Kendujhar",
        "Malkangiri",
        "Nabarangapur",
        "Paradip",
        "Parlakhemundi",
        "Pattamundai",
        "Phulabani",
        "Puri",
        "Rairangpur",
        "Rajagangapur",
        "Raurkela",
        "Rayagada",
        "Sambalpur",
        "Soro",
        "Sunabeda",
        "Sundargarh",
        "Talcher",
        "Tarbha",
        "Titlagarh",
      ],
      Puducherry: ["Karaikal", "Mahe", "Pondicherry*", "Yanam"],
      Punjab: [
        "Amritsar",
        "Barnala",
        "Batala",
        "Bathinda",
        "Dhuri",
        "Faridkot",
        "Fazilka",
        "Firozpur",
        "Firozpur Cantt.",
        "Gobindgarh",
        "Gurdaspur",
        "Hoshiarpur",
        "Jagraon",
        "Jalandhar Cantt.",
        "Jalandhar",
        "Kapurthala",
        "Khanna",
        "Kharar",
        "Kot Kapura",
        "Longowal",
        "Ludhiana",
        "Malerkotla",
        "Malout",
        "Mansa",
        "Moga",
        "Mohali",
        "Morinda, India",
        "Mukerian",
        "Muktsar",
        "Nabha",
        "Nakodar",
        "Nangal",
        "Nawanshahr",
        "Pathankot",
        "Patiala",
        "Pattran",
        "Patti",
        "Phagwara",
        "Phillaur",
        "Qadian",
        "Raikot",
        "Rajpura",
        "Rampura Phul",
        "Rupnagar",
        "Samana",
        "Sangrur",
        "Sirhind Fatehgarh Sahib",
        "Sujanpur",
        "Sunam",
        "Talwara",
        "Tarn Taran",
        "Urmar Tanda",
        "Zira",
        "Zirakpur",
      ],
      UttarPradesh: [
        "Achhnera",
        "Agra",
        "Aligarh",
        "Allahabad",
        "Amroha",
        "Azamgarh",
        "Bahraich",
        "Chandausi",
        "Etawah",
        "Firozabad",
        "Fatehpur Sikri",
        "Hapur",
        "Hardoi *",
        "Jhansi",
        "Kalpi",
        "Kanpur",
        "Khair",
        "Laharpur",
        "Lakhimpur",
        "Lal Gopalganj Nindaura",
        "Lalitpur",
        "Lalganj",
        "Lar",
        "Loni",
        "Lucknow*",
        "Mathura",
        "Meerut",
        "Modinagar",
        "Moradabad",
        "Nagina",
        "Najibabad",
        "Nakur",
        "Nanpara",
        "Naraura",
        "Naugawan Sadat",
        "Nautanwa",
        "Nawabganj",
        "Nehtaur",
        "Niwai",
        "Noida",
        "Noorpur",
        "Obra",
        "Orai",
        "Padrauna",
        "Palia Kalan",
        "Parasi",
        "Phulpur",
        "Pihani",
        "Pilibhit",
        "Pilkhuwa",
        "Powayan",
        "Pukhrayan",
        "Puranpur",
        "Purquazi",
        "Purwa",
        "Rae Bareli",
        "Rampur",
        "Rampur Maniharan",
        "Rampur Maniharan",
        "Rasra",
        "Rath",
        "Renukoot",
        "Reoti",
        "Robertsganj",
        "Rudauli",
        "Rudrapur",
        "Sadabad",
        "Safipur",
        "Saharanpur",
        "Sahaspur",
        "Sahaswan",
        "Sahawar",
        "Sahjanwa",
        "Saidpur",
        "Sambhal",
        "Samdhan",
        "Samthar",
        "Sandi",
        "Sandila",
        "Sardhana",
        "Seohara",
        "Shahabad, Hardoi",
        "Shahabad, Rampur",
        "Shahganj",
        "Shahjahanpur",
        "Shamli",
        "Shamsabad, Agra",
        "Shamsabad, Farrukhabad",
        "Sherkot",
        "Shikarpur, Bulandshahr",
        "Shikohabad",
        "Shishgarh",
        "Siana",
        "Sikanderpur",
        "Sikandra Rao",
        "Sikandrabad",
        "Sirsaganj",
        "Sirsi",
        "Sitapur",
        "Soron",
        "Suar",
        "Sultanpur",
        "Sumerpur",
        "Tanda",
        "Thakurdwara",
        "Thana Bhawan",
        "Tilhar",
        "Tirwaganj",
        "Tulsipur",
        "Tundla",
        "Ujhani",
        "Unnao",
        "Utraula",
        "Varanasi",
        "Vrindavan",
        "Warhapur",
        "Zaidpur",
        "Zamania",
      ],
      Uttarakhand: [
        "Bageshwar",
        "Dehradun",
        "Haldwani-cum-Kathgodam",
        "Hardwar",
        "Kashipur",
        "Manglaur",
        "Mussoorie",
        "Nagla",
        "Nainital",
        "Pauri",
        "Pithoragarh",
        "Ramnagar",
        "Rishikesh",
        "Roorkee",
        "Rudrapur",
        "Sitarganj",
        "Srinagar",
        "Tehri",
      ],
      WestBengal: [
        "Adra",
        "Alipurduar",
        "Arambagh",
        "Asansol",
        "Baharampur",
        "Balurghat",
        "Bankura",
        "Darjiling",
        "English Bazar",
        "Gangarampur",
        "Habra",
        "Hugli-Chinsurah",
        "Jalpaiguri",
        "Jhargram",
        "Kalimpong",
        "Kharagpur",
        "Kolkata",
        "Mainaguri",
        "Malda",
        "Mathabhanga",
        "Medinipur",
        "Memari",
        "Monoharpur",
        "Murshidabad",
        "Nabadwip",
        "Naihati",
        "Panchla",
        "Pandua",
        "Paschim Punropara",
        "Purulia",
        "Raghunathpur",
        "Raghunathganj",
        "Raiganj",
        "Rampurhat",
        "Ranaghat",
        "Sainthia",
        "Santipur",
        "Siliguri",
        "Sonamukhi",
        "Srirampore",
        "Suri",
        "Taki",
        "Tamluk",
        "Tarakeswar",
      ],
    },
  ];

  const [listcity, setListCity] = useState([]);

  const StateChangeHandler = (e) => {
    const selectedstate = e.target.value;
    setListCity(statescities.at(0)[selectedstate]);
  };

  const Handlersubmit = (e) => {
    e.preventDefault();
    console.log(listcity);
  };

  return (
    <>
      <Container maxW="container.sm" color="black">
        <Heading
          bgGradient="linear(to-r,green.500,red.300,blue.600,)"
          bgClip="text"
          textAlign="center"
        >
          State And City
        </Heading>
        <SimpleGrid columns={2} spacing={10} m={5}>
          <FormLabel fontWeight="bold">State</FormLabel>
          <Select placeholder="Select State" onChange={StateChangeHandler}>
            {Object.keys(statescities[0]).map((item, i) => (
              <option key={i}>{item}</option>
            ))}
          </Select>
          <FormLabel fontWeight="bold">City</FormLabel>
          <Select placeholder="Select City">
            {listcity.map((item, i) => (
              <option key={i}>{item}</option>
            ))}
          </Select>
        </SimpleGrid>
        <Stack spacing={4} direction="row">
          <Button
            colorScheme="teal"
            size="lg"
            align="center"
            onClick={Handlersubmit}
          >
            ADD
          </Button>
        </Stack>
      </Container>
    </>
  );
};

export default StateCityData;
